version: '2'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=lees.org.uk
      - SUBDOMAINS=ogrdb
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=william@lees.org.uk  #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - /root/ogrdb_docker/config/nginx:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  flask:
    image: my_flask
    container_name: flask
    volumes:
        - /root/ogrdb_docker/config/flask:/config
        - /backup:/backup
    restart: unless-stopped 
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=gsdfgtwevdfg
      - TZ=Europe/London
      - MYSQL_DATABASE=ogrdb #optional
      - MYSQL_USER=ogrdb #optional
      - MYSQL_PASSWORD=ogrdb #optional
    volumes:
      - /root/ogrdb_docker/config/mysql:/config
    ports:
      - 3306:3306
    restart: unless-stopped
