version: '2'

services:
  ogrdb_flask:
    image: my_flask
    container_name: flask
    volumes:
        - /root/ogrdb_docker/config/flask:/config
        - /backup:/backup
        - /root/ogrdb_docker/ogre:/ogre
    restart: unless-stopped 
networks:
    default:
        external: true
        name: digby_network
