version: '2'

services:
  ogrdb_flask:
    image: my_flask
    container_name: ogrdb_flask
    volumes:
        - /root/ogrdb_docker/config/flask:/config
        - /root/ogrdb_docker/backup:/backup
        - /root/ogrdb_docker/ogre:/ogre
        - /root/digby_infra/config:/infra_config        
    restart: unless-stopped 
networks:
    default:
        external: true
        name: digby_network
